In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [30]:
car =  pd.read_csv("../../data/good_car_data.csv")
car.head(5)

Unnamed: 0                    name   company  year   Price  kms_driven  \
0           0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1           1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2           2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3           3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4           4               Ford Figo      Ford  2012  175000       41000   

  fuel_type  
0    Petrol  
1    Diesel  
2    Petrol  
3    Diesel  
4    Diesel

In [5]:
car.shape

(816, 7)

In [34]:
car.columns

Index(['Unnamed: 0', 'name', 'company', 'year', 'Price', 'kms_driven',
       'fuel_type'],
      dtype='object')

In [6]:
X=car[['name','company','year','kms_driven','fuel_type']]
y=car['Price']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [16]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [17]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [18]:
X_train

name    company  year  kms_driven fuel_type
15                Audi Q7       Audi  2014       16934    Diesel
310       Mahindra XUV500   Mahindra  2014       47000    Diesel
772        Tata Indica V2       Tata  2005       80000    Diesel
748             Tata Nano       Tata  2013        7000    Petrol
677     Maruti Suzuki SX4     Maruti  2016       85960    Diesel
..                    ...        ...   ...         ...       ...
54   Mahindra Scorpio S10   Mahindra  2015       35000    Diesel
277     Chevrolet Beat LS  Chevrolet  2010       56000    Petrol
125       Honda Amaze 1.5      Honda  2013       45000    Diesel
651      Volvo S80 Summum      Volvo  2015       42000    Diesel
798   Maruti Suzuki Swift     Maruti  2016      146000    Diesel

[652 rows x 5 columns]

In [22]:
XX_train =column_trans.fit_transform(X_train).toarray()

In [35]:
XX_train.shape

(652, 284)

In [38]:
XX_train[0]

array([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e

In [36]:
y_train.shape

(652,)

In [37]:
y_train[0]

80000

In [41]:
XX_train=pd.DataFrame(XX_train)

In [42]:
XX_train.merge(y_train.to_frame(), left_index=True, right_index=True)


0    1    2    3    4    5    6    7    8    9  ...  275  276  277  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
5    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
7    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
647  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
648  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
649  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
650  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
651  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     278  279  280  281     282       283    Price  
0    0.0  1.0  0.0  0.0  2014.0   16934.0    80000  
2    0.0  1.0  0.0  0.0  2005.0   80000.0   325000  
3    0.0  0.0  0.0  1.0  2013.0    7000.0   575000  
5    0.0  0.0  0.0  1.0  2006.0   56000.0   190000  
7    0.0  0.0  0.0  1.0  2010.0   60000.0   250000  
..   ...  ...  ...  ...     ...       ...      ...  
647  0.0  1.0  0.0  0.0  2015.0   35000.0   800000  
648  0.0  0.0  0.0  1.0  2010.0   56000.0   450000  
649  0.0  1.0  0.0  0.0  2013.0   45000.0  1000000  
650  1.0  1.0  0.0  0.0  2015.0   42000.0  1510000  
651  0.0  1.0  0.0  0.0  2016.0  146000.0  1850000  

[517 rows x 285 columns]

In [43]:
XX_train.shape

(652, 284)

In [44]:
arief_train=XX_train.values
arief_train

array([[     0.,      0.,      0., ...,      0.,   2014.,  16934.],
       [     0.,      0.,      0., ...,      0.,   2014.,  47000.],
       [     0.,      0.,      0., ...,      0.,   2005.,  80000.],
       ...,
       [     0.,      0.,      0., ...,      0.,   2013.,  45000.],
       [     0.,      0.,      0., ...,      0.,   2015.,  42000.],
       [     0.,      0.,      0., ...,      0.,   2016., 146000.]])

In [28]:
YY_train= column_trans.fit_transform(X_test).toarray()
YY_train.shape

(164, 284)

In [10]:
lr=LinearRegression()

In [11]:
pipe=make_pipeline(column_trans,lr)

In [12]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Pe

In [13]:

y_pred=pipe.predict(X_test)

In [14]:
r2_score(y_test,y_pred)

0.7759881515594951

In [16]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))


In [18]:
type(scores)

list

In [19]:
np.argmax(scores)

144

In [20]:
scores[np.argmax(scores)]

0.9210013759723452

In [21]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([419640.52960552])

In [22]:
import pickle
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([419640.52960552])